### ISSUE TITLE
--only appears to be broken

### ISSUE THREAD

**Issue by sdt16** [dalance/procs#85]
Whenever I use --only, procs panics or outputs nothing.

This is all on x86_64.

With rust nightly (rustc 1.49.0-nightly (f2bbdd0a3 2020-11-04)):

```
schuyler@laptop:~/dunst$ RUST_BACKTRACE=1 procs --no-header --only Pid i3
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/schuyler/.cargo/registry/src/github.com-1ecc6299db9ec823/procs-0.10.8/src/view.rs:150:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f2bbdd0a3257cc980c934a92c5bf9808cf31728c/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/f2bbdd0a3257cc980c934a92c5bf9808cf31728c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/f2bbdd0a3257cc980c934a92c5bf9808cf31728c/library/core/src/panicking.rs:69:5
   3: procs::view::View::filter
   4: procs::run
   5: procs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With stable (1.49.0):

```
schuyler@laptop:~/dunst$ procs --no-header --only Pid i3
schuyler@laptop:~/dunst$ echo $?
0
```

however, notice the lowercase p in 'pid':

```
schuyler@laptop:~/dunst$ procs --no-header --only pid i3
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/schuyler/.cargo/registry/src/github.com-1ecc6299db9ec823/procs-0.10.8/src/view.rs:150:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I have some time I'll try to dig into this myself.

**Comment by dalance** [comment]
Thank you for your report.

The crash seems to occur randomly caused by column kind search order.
`pid` matches `PID` or `PPID` randomly, and `PPID` becomes crash if `PPID` is not found in column config.

I changed the way of kind search, and added error handling.

**Comment by sdt16** [comment]
Fantastic! Thanks for the quick response. I'll try to test it sometime today.
